### ISSUE TITLE
Building wheel for rapidfuzz ... Error

### ISSUE THREAD

**Issue by ghost** [rhasspy/rhasspy-satellite#1]
```
Building wheels for collected packages: rapidfuzz
  Building wheel for rapidfuzz (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/pi/rhasspy-satellite/.venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-netx039t/rapidfuzz/setup.py'"'"'; __file__='"'"'/tmp/pip-install-netx039t/rapidfuzz/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-x7bpmq7r
       cwd: /tmp/pip-install-netx039t/rapidfuzz/
  Complete output (31 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-armv6l-3.7
  creating build/lib.linux-armv6l-3.7/rapidfuzz
  copying src/rapidfuzz/fuzz.py -> build/lib.linux-armv6l-3.7/rapidfuzz
  copying src/rapidfuzz/process.py -> build/lib.linux-armv6l-3.7/rapidfuzz
  copying src/rapidfuzz/utils.py -> build/lib.linux-armv6l-3.7/rapidfuzz
  copying src/rapidfuzz/__init__.py -> build/lib.linux-armv6l-3.7/rapidfuzz
  running egg_info
  writing src/rapidfuzz.egg-info/PKG-INFO
  writing dependency_links to src/rapidfuzz.egg-info/dependency_links.txt
  writing top-level names to src/rapidfuzz.egg-info/top_level.txt
  reading manifest file 'src/rapidfuzz.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*.hpp' under directory 'cpp/src'
  warning: no files found matching '*.txx' under directory 'cpp/src'
  warning: no files found matching '*' under directory 'cpp/extern/boost'
  warning: no files found matching '*.hpp' under directory 'python/src'
  writing manifest file 'src/rapidfuzz.egg-info/SOURCES.txt'
  running build_ext
  building 'rapidfuzz.levenshtein' extension
  creating build/temp.linux-armv6l-3.7
  creating build/temp.linux-armv6l-3.7/src
  arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Isrc/rapidfuzz-cpp/src -Isrc/rapidfuzz-cpp/extern -I/home/pi/rhasspy-satellite/.venv/include -I/usr/include/python3.7m -c src/py_levenshtein.cpp -o build/temp.linux-armv6l-3.7/src/py_levenshtein.o -O3 -std=c++14 -DVERSION_INFO="0.7.4"
  src/py_levenshtein.cpp:7:10: fatal error: levenshtein.hpp: No such file or directory
   #include "levenshtein.hpp"
            ^~~~~~~~~~~~~~~~~
  compilation terminated.
  error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for rapidfuzz
  Running setup.py clean for rapidfuzz
```

Tryed installing "sudo pip3 install python-Levenshtein" and "sudo apt-get install libffi-dev" but none worked.

**Comment by dannyqwertz** [comment]
I've got the same issue as described above, freshly set up pi3b+ with buster.
Trying to run rhasspy-satellite after the failed compile outputs the following error message:

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/dne/rhasspy-satellite/rhasspy-server-hermes/rhasspyserver_hermes/__main__.py", line 64, in <module>
    from swagger_ui import quart_api_doc
ModuleNotFoundError: No module named 'swagger_ui'
```

**Comment by ghost** [comment]
I solved my rapidfuzz error looking at my requirements.txt file, it was not the same as the one they have although i did clone the repo.
Swagger-ui is a requirement and your error says its not found so...
Check your requirements.txt and make sure it's the same, if not, modify it.
